### ISSUE TITLE
Help fails to load on FreeBSD with Python 3.6

### ISSUE THREAD

**Issue by kiwichris** [vuvova/gdb-tools#11]
The `help.md` fails to load with Python 3.6 because of ...

 `.. the fourth \xe2\x80\x94 boolean OR. Just like in C, AND and OR`

The error is:

```
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/opt/work/chris/gdb/duel/__init__.py", line 5, in <module>
    from duel.help import *
  File "/opt/work/chris/gdb/duel/help.py", line 15, in <module>
    with open(__file__.rstrip("pyc") + "md") as f: LONGHELP = ''.join(f)
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
```

**Comment by vuvova** [comment]
already fixed in e33cb869dc796d8ce294d97a4a53e59b0f21a683

**Comment by vuvova** [comment]
I've released a new version with this fix

**Comment by kiwichris** [comment]
Oh sorry, I did not check the repo. Thanks for the update.
